PUT https://localhost:5000/api/items
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxNiIsInVuaXF1ZV9uYW1lIjoiYWRtaW4iLCJyb2xlIjpbIkVtcGxveWVlIiwiQWRtaW4iXSwibmJmIjoxNzA2NjA4Njk4LCJleHAiOjE3MDcyMTM0OTgsImlhdCI6MTcwNjYwODY5OH0.ZzwgW9C74hQQfCQRkApsO7FeVW5hcb8lh1P63uT7BTN_5Gi-t3goTlrXVKrWEcig3scIwTMCrSfr1nz9v7Qt9Q
Content-Type: application/json

{
  "Id": 3,
  "Name": "edited3",
  "Description": "edited3",
  "CategoryId": 1,
  "Price": 100500,
  "Quantity": 100500,
  "MeasureUnitId": 1,
  "ImageUrl": "edited3",
  "Features": [
    {
      "Item1": "edited",
      "Item2": "edited"
    }
  ]
}