GET https://localhost:7141/api/users/
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxNiIsInVuaXF1ZV9uYW1lIjoiYWRtaW4iLCJyb2xlIjpbIkVtcGxveWVlIiwiQWRtaW4iXSwibmJmIjoxNzA2NjA4Njk4LCJleHAiOjE3MDcyMTM0OTgsImlhdCI6MTcwNjYwODY5OH0.ZzwgW9C74hQQfCQRkApsO7FeVW5hcb8lh1P63uT7BTN_5Gi-t3goTlrXVKrWEcig3scIwTMCrSfr1nz9v7Qt9Q